const EUROPEAN_CLUB_PROFILES = {"Ajax":{"attack":73,"midfield":73,"defense":71,"goalkeeper":70,"overall":72},"PSV":{"attack":76,"midfield":77,"defense":74,"goalkeeper":72,"overall":75},"Feyenoord":{"attack":72,"midfield":72,"defense":73,"goalkeeper":69,"overall":72},"FC Porto":{"attack":74,"midfield":75,"defense":73,"goalkeeper":72,"overall":74},"Benfica":{"attack":74,"midfield":73,"defense":73,"goalkeeper":71,"overall":73},"Sporting CP":{"attack":76,"midfield":78,"defense":77,"goalkeeper":71,"overall":76},"Celtic":{"attack":73,"midfield":74,"defense":73,"goalkeeper":70,"overall":73},"Rangers":{"attack":71,"midfield":71,"defense":70,"goalkeeper":71,"overall":71},"Club Brugge":{"attack":70,"midfield":71,"defense":70,"goalkeeper":67,"overall":70},"Anderlecht":{"attack":68,"midfield":67,"defense":68,"goalkeeper":68,"overall":68},"Galatasaray":{"attack":76,"midfield":75,"defense":74,"goalkeeper":71,"overall":75},"Fenerbahçe":{"attack":76,"midfield":75,"defense":75,"goalkeeper":76,"overall":76},"Beşiktaş":{"attack":75,"midfield":76,"defense":72,"goalkeeper":71,"overall":74},"Olympiacos":{"attack":74,"midfield":73,"defense":74,"goalkeeper":71,"overall":73},"PAOK":{"attack":74,"midfield":74,"defense":72,"goalkeeper":69,"overall":73},"Red Star":{"attack":65,"midfield":65,"defense":64,"goalkeeper":66,"overall":65},"Dinamo Zagreb":{"attack":69,"midfield":70,"defense":68,"goalkeeper":65,"overall":68},"Salzburg":{"attack":67,"midfield":67,"defense":67,"goalkeeper":63,"overall":66},"Shakhtar":{"attack":69,"midfield":70,"defense":69,"goalkeeper":68,"overall":69},"Dynamo Kyiv":{"attack":70,"midfield":71,"defense":70,"goalkeeper":63,"overall":69},"Malmö":{"attack":67,"midfield":67,"defense":68,"goalkeeper":66,"overall":67},"Slavia Prague":{"attack":72,"midfield":73,"defense":72,"goalkeeper":72,"overall":72},"Sparta Prague":{"attack":70,"midfield":69,"defense":72,"goalkeeper":70,"overall":70},"Young Boys":{"attack":69,"midfield":71,"defense":66,"goalkeeper":65,"overall":68},"Basel":{"attack":67,"midfield":68,"defense":68,"goalkeeper":62,"overall":67},"APOEL":{"attack":65,"midfield":66,"defense":67,"goalkeeper":68,"overall":66},"Ferencváros":{"attack":70,"midfield":70,"defense":69,"goalkeeper":66,"overall":69},"Midtjylland":{"attack":69,"midfield":70,"defense":70,"goalkeeper":68,"overall":69},"Bodø/Glimt":{"attack":69,"midfield":70,"defense":70,"goalkeeper":64,"overall":69},"AZ Alkmaar":{"attack":70,"midfield":70,"defense":69,"goalkeeper":66,"overall":69},"Braga":{"attack":73,"midfield":73,"defense":73,"goalkeeper":67,"overall":72},"Trabzonspor":{"attack":72,"midfield":72,"defense":71,"goalkeeper":78,"overall":73}};

Object.assign(EUROPEAN_CLUB_PROFILES, {
  "Copenhagen": {"attack":71,"midfield":72,"defense":71,"goalkeeper":70,"overall":71},
  "Union Saint-Gilloise": {"attack":72,"midfield":73,"defense":71,"goalkeeper":68,"overall":71},
  "Kairat Almaty": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Pafos": {"attack":65,"midfield":66,"defense":65,"goalkeeper":64,"overall":65},
  "Qarabag": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":66},
  "Sturm Graz": {"attack":69,"midfield":70,"defense":68,"goalkeeper":67,"overall":69},
  "Genk": {"attack":72,"midfield":73,"defense":72,"goalkeeper":69,"overall":72},
  "Ludogorets": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Viktoria Plzen": {"attack":70,"midfield":71,"defense":70,"goalkeeper":68,"overall":70},
  "Panathinaikos": {"attack":73,"midfield":74,"defense":72,"goalkeeper":70,"overall":73},
  "Maccabi Tel-Aviv": {"attack":68,"midfield":69,"defense":68,"goalkeeper":67,"overall":68},
  "Go Ahead Eagles": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Utrecht": {"attack":71,"midfield":72,"defense":70,"goalkeeper":68,"overall":71},
  "Brann": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "FCSB": {"attack":69,"midfield":70,"defense":70,"goalkeeper":67,"overall":69},
  "Noah": {"attack":64,"midfield":65,"defense":64,"goalkeeper":63,"overall":64},
  "SK Rapid": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Zrinjski": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Rijeka": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "AEK Larnaca": {"attack":66,"midfield":67,"defense":66,"goalkeeper":65,"overall":66},
  "Omonoia": {"attack":66,"midfield":67,"defense":66,"goalkeeper":64,"overall":66},
  "Sigma Olomouc": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "KuPS": {"attack":65,"midfield":66,"defense":65,"goalkeeper":64,"overall":65},
  "Lincoln Red Imps": {"attack":59,"midfield":60,"defense":59,"goalkeeper":58,"overall":59},
  "AEK Athens": {"attack":72,"midfield":73,"defense":72,"goalkeeper":69,"overall":72},
  "Breidablik": {"attack":65,"midfield":66,"defense":65,"goalkeeper":63,"overall":65},
  "Drita": {"attack":61,"midfield":62,"defense":61,"goalkeeper":60,"overall":61},
  "Hamrun Spartans": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Shkendija": {"attack":62,"midfield":63,"defense":62,"goalkeeper":61,"overall":62},
  "Jagiellonia": {"attack":68,"midfield":69,"defense":68,"goalkeeper":65,"overall":68},
  "Lech Poznan": {"attack":69,"midfield":70,"defense":69,"goalkeeper":67,"overall":69},
  "Legia Warszawa": {"attack":70,"midfield":71,"defense":69,"goalkeeper":67,"overall":70},
  "Rakow Czestochowa": {"attack":70,"midfield":71,"defense":71,"goalkeeper":68,"overall":71},
  "Shamrock Rovers": {"attack":64,"midfield":65,"defense":64,"goalkeeper":63,"overall":64},
  "Shelbourne": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Universitatea Craiova": {"attack":67,"midfield":68,"defense":68,"goalkeeper":65,"overall":67},
  "Aberdeen": {"attack":68,"midfield":69,"defense":69,"goalkeeper":66,"overall":68},
  "Slovan Bratislava": {"attack":66,"midfield":67,"defense":66,"goalkeeper":64,"overall":66},
  "Celje": {"attack":65,"midfield":66,"defense":65,"goalkeeper":63,"overall":65},
  "Hacken": {"attack":68,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "Lausanne-Sport": {"attack":66,"midfield":67,"defense":67,"goalkeeper":64,"overall":66},
  "Samsunspor": {"attack":69,"midfield":70,"defense":69,"goalkeeper":67,"overall":69}
});

const EUROPE_2025_26 = {
  UCL: [
    { name: "Paris Saint-Germain", id: "psg" },
    { name: "Tottenham", id: "tottenham" },
    { name: "Liverpool", id: "liverpool" },
    { name: "Arsenal", id: "arsenal" },
    { name: "Manchester City", id: "man-city" },
    { name: "Chelsea", id: "chelsea" },
    { name: "Napoli", id: "napoli" },
    { name: "Inter", id: "inter" },
    { name: "Atalanta", id: "atalanta" },
    { name: "Juventus", id: "juventus" },
    { name: "Barcelona", id: "barcelona" },
    { name: "Real Madrid", id: "real-madrid" },
    { name: "Atletico Madrid", id: "atletico" },
    { name: "Athletic Club", id: "athletic-bilbao" },
    { name: "Bayern Munich", id: "bayern" },
    { name: "Bayer Leverkusen", id: "leverkusen" },
    { name: "Eintracht Frankfurt", id: "frankfurt" },
    { name: "Dortmund", id: "dortmund" },
    { name: "Marseille", id: "marseille" },
    { name: "Monaco", id: "monaco" },
    { name: "PSV", profile: "PSV" },
    { name: "Ajax", profile: "Ajax" },
    { name: "Sporting CP", profile: "Sporting CP" },
    { name: "Union Saint-Gilloise", profile: "Union Saint-Gilloise" },
    { name: "Galatasaray", profile: "Galatasaray" },
    { name: "Slavia Praha", profile: "Slavia Prague" },
    { name: "Olympiacos", profile: "Olympiacos" },
    { name: "Newcastle United", id: "newcastle" },
    { name: "Villarreal", id: "villarreal" },
    { name: "Bodø/Glimt", profile: "Bodø/Glimt" },
    { name: "Copenhagen", profile: "Copenhagen" },
    { name: "Kairat Almaty", profile: "Kairat Almaty" },
    { name: "Pafos", profile: "Pafos" },
    { name: "Qarabağ", profile: "Qarabag" },
    { name: "Benfica", profile: "Benfica" },
    { name: "Club Brugge", profile: "Club Brugge" }
  ],
  UEL: [
    { name: "Salzburg", profile: "Salzburg" },
    { name: "Sturm Graz", profile: "Sturm Graz" },
    { name: "Genk", profile: "Genk" },
    { name: "Ludogorets", profile: "Ludogorets" },
    { name: "GNK Dinamo", profile: "Dinamo Zagreb" },
    { name: "Viktoria Plzeň", profile: "Viktoria Plzen" },
    { name: "Midtjylland", profile: "Midtjylland" },
    { name: "Aston Villa", id: "aston-villa" },
    { name: "Nottingham Forest", id: "nottingham-forest" },
    { name: "Lille", id: "lille" },
    { name: "Lyon", id: "lyon" },
    { name: "Nice", id: "nice" },
    { name: "Stuttgart", id: "stuttgart" },
    { name: "Freiburg", id: "freiburg" },
    { name: "Panathinaikos", profile: "Panathinaikos" },
    { name: "PAOK", profile: "PAOK" },
    { name: "Ferencváros", profile: "Ferencváros" },
    { name: "Maccabi Tel-Aviv", profile: "Maccabi Tel-Aviv" },
    { name: "Bologna", id: "bologna" },
    { name: "Roma", id: "roma" },
    { name: "Feyenoord", profile: "Feyenoord" },
    { name: "Go Ahead Eagles", profile: "Go Ahead Eagles" },
    { name: "Utrecht", profile: "Utrecht" },
    { name: "Brann", profile: "Brann" },
    { name: "Braga", profile: "Braga" },
    { name: "Porto", profile: "FC Porto" },
    { name: "FCSB", profile: "FCSB" },
    { name: "Celtic", profile: "Celtic" },
    { name: "Rangers", profile: "Rangers" },
    { name: "Crvena Zvezda", profile: "Red Star" },
    { name: "Real Betis", id: "real-betis" },
    { name: "Celta", id: "celta" },
    { name: "Malmö", profile: "Malmö" },
    { name: "Basel", profile: "Basel" },
    { name: "Young Boys", profile: "Young Boys" },
    { name: "Fenerbahçe", profile: "Fenerbahçe" }
  ],
  UECL: [
    { name: "Noah", profile: "Noah" },
    { name: "SK Rapid", profile: "SK Rapid" },
    { name: "Zrinjski", profile: "Zrinjski" },
    { name: "Rijeka", profile: "Rijeka" },
    { name: "AEK Larnaca", profile: "AEK Larnaca" },
    { name: "Omonoia", profile: "Omonoia" },
    { name: "Sigma Olomouc", profile: "Sigma Olomouc" },
    { name: "Sparta Praha", profile: "Sparta Prague" },
    { name: "Crystal Palace", id: "crystal-palace" },
    { name: "KuPS", profile: "KuPS" },
    { name: "Strasbourg", id: "strasbourg" },
    { name: "Mainz", id: "mainz" },
    { name: "Lincoln Red Imps", profile: "Lincoln Red Imps" },
    { name: "AEK Athens", profile: "AEK Athens" },
    { name: "Breidablik", profile: "Breidablik" },
    { name: "Fiorentina", id: "fiorentina" },
    { name: "Drita", profile: "Drita" },
    { name: "Hamrun Spartans", profile: "Hamrun Spartans" },
    { name: "AZ Alkmaar", profile: "AZ Alkmaar" },
    { name: "Shkendija", profile: "Shkendija" },
    { name: "Jagiellonia", profile: "Jagiellonia" },
    { name: "Lech Poznań", profile: "Lech Poznan" },
    { name: "Legia Warszawa", profile: "Legia Warszawa" },
    { name: "Raków Częstochowa", profile: "Rakow Czestochowa" },
    { name: "Shamrock Rovers", profile: "Shamrock Rovers" },
    { name: "Shelbourne", profile: "Shelbourne" },
    { name: "Universitatea Craiova", profile: "Universitatea Craiova" },
    { name: "Aberdeen", profile: "Aberdeen" },
    { name: "Slovan Bratislava", profile: "Slovan Bratislava" },
    { name: "Celje", profile: "Celje" },
    { name: "Rayo Vallecano", id: "rayovallecano" },
    { name: "Häcken", profile: "Hacken" },
    { name: "Lausanne-Sport", profile: "Lausanne-Sport" },
    { name: "Samsunspor", profile: "Samsunspor" },
    { name: "Dynamo Kyiv", profile: "Dynamo Kyiv" },
    { name: "Shakhtar Donetsk", profile: "Shakhtar" }
  ]
};