const EUROPEAN_CLUB_PROFILES = {"Ajax":{"attack":73,"midfield":73,"defense":71,"goalkeeper":70,"overall":72},"PSV":{"attack":76,"midfield":77,"defense":74,"goalkeeper":72,"overall":75},"Feyenoord":{"attack":72,"midfield":72,"defense":73,"goalkeeper":69,"overall":72},"FC Porto":{"attack":74,"midfield":75,"defense":73,"goalkeeper":72,"overall":74},"Benfica":{"attack":74,"midfield":73,"defense":73,"goalkeeper":71,"overall":73},"Sporting CP":{"attack":76,"midfield":78,"defense":77,"goalkeeper":71,"overall":76},"Celtic":{"attack":73,"midfield":74,"defense":73,"goalkeeper":70,"overall":73},"Rangers":{"attack":71,"midfield":71,"defense":70,"goalkeeper":71,"overall":71},"Club Brugge":{"attack":70,"midfield":71,"defense":70,"goalkeeper":67,"overall":70},"Anderlecht":{"attack":68,"midfield":67,"defense":68,"goalkeeper":68,"overall":68},"Galatasaray":{"attack":76,"midfield":75,"defense":74,"goalkeeper":71,"overall":75},"Fenerbahçe":{"attack":76,"midfield":75,"defense":75,"goalkeeper":76,"overall":76},"Beşiktaş":{"attack":75,"midfield":76,"defense":72,"goalkeeper":71,"overall":74},"Olympiacos":{"attack":74,"midfield":73,"defense":74,"goalkeeper":71,"overall":73},"PAOK":{"attack":74,"midfield":74,"defense":72,"goalkeeper":69,"overall":73},"Red Star":{"attack":65,"midfield":65,"defense":64,"goalkeeper":66,"overall":65},"Dinamo Zagreb":{"attack":69,"midfield":70,"defense":68,"goalkeeper":65,"overall":68},"Salzburg":{"attack":67,"midfield":67,"defense":67,"goalkeeper":63,"overall":66},"Shakhtar":{"attack":69,"midfield":70,"defense":69,"goalkeeper":68,"overall":69},"Dynamo Kyiv":{"attack":70,"midfield":71,"defense":70,"goalkeeper":63,"overall":69},"Malmö":{"attack":67,"midfield":67,"defense":68,"goalkeeper":66,"overall":67},"Slavia Prague":{"attack":72,"midfield":73,"defense":72,"goalkeeper":72,"overall":72},"Sparta Prague":{"attack":70,"midfield":69,"defense":72,"goalkeeper":70,"overall":70},"Young Boys":{"attack":69,"midfield":71,"defense":66,"goalkeeper":65,"overall":68},"Basel":{"attack":67,"midfield":68,"defense":68,"goalkeeper":62,"overall":67},"APOEL":{"attack":65,"midfield":66,"defense":67,"goalkeeper":68,"overall":66},"Ferencváros":{"attack":70,"midfield":70,"defense":69,"goalkeeper":66,"overall":69},"Midtjylland":{"attack":69,"midfield":70,"defense":70,"goalkeeper":68,"overall":69},"Bodø/Glimt":{"attack":69,"midfield":70,"defense":70,"goalkeeper":64,"overall":69},"AZ Alkmaar":{"attack":70,"midfield":70,"defense":69,"goalkeeper":66,"overall":69},"Braga":{"attack":73,"midfield":73,"defense":73,"goalkeeper":67,"overall":72},"Trabzonspor":{"attack":72,"midfield":72,"defense":71,"goalkeeper":78,"overall":73}};

Object.assign(EUROPEAN_CLUB_PROFILES, {
  "Copenhagen": {"attack":71,"midfield":72,"defense":71,"goalkeeper":70,"overall":71},
  "Union Saint-Gilloise": {"attack":72,"midfield":73,"defense":71,"goalkeeper":68,"overall":71},
  "Kairat Almaty": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Pafos": {"attack":65,"midfield":66,"defense":65,"goalkeeper":64,"overall":65},
  "Qarabag": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":66},
  "Sturm Graz": {"attack":69,"midfield":70,"defense":68,"goalkeeper":67,"overall":69},
  "Genk": {"attack":72,"midfield":73,"defense":72,"goalkeeper":69,"overall":72},
  "Ludogorets": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Viktoria Plzen": {"attack":70,"midfield":71,"defense":70,"goalkeeper":68,"overall":70},
  "Panathinaikos": {"attack":73,"midfield":74,"defense":72,"goalkeeper":70,"overall":73},
  "Maccabi Tel-Aviv": {"attack":68,"midfield":69,"defense":68,"goalkeeper":67,"overall":68},
  "Go Ahead Eagles": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Utrecht": {"attack":71,"midfield":72,"defense":70,"goalkeeper":68,"overall":71},
  "Brann": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "FCSB": {"attack":69,"midfield":70,"defense":70,"goalkeeper":67,"overall":69},
  "Noah": {"attack":64,"midfield":65,"defense":64,"goalkeeper":63,"overall":64},
  "SK Rapid": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Zrinjski": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Rijeka": {"attack":67,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "AEK Larnaca": {"attack":66,"midfield":67,"defense":66,"goalkeeper":65,"overall":66},
  "Omonoia": {"attack":66,"midfield":67,"defense":66,"goalkeeper":64,"overall":66},
  "Sigma Olomouc": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "KuPS": {"attack":65,"midfield":66,"defense":65,"goalkeeper":64,"overall":65},
  "Lincoln Red Imps": {"attack":59,"midfield":60,"defense":59,"goalkeeper":58,"overall":59},
  "AEK Athens": {"attack":72,"midfield":73,"defense":72,"goalkeeper":69,"overall":72},
  "Breidablik": {"attack":65,"midfield":66,"defense":65,"goalkeeper":63,"overall":65},
  "Drita": {"attack":61,"midfield":62,"defense":61,"goalkeeper":60,"overall":61},
  "Hamrun Spartans": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Shkendija": {"attack":62,"midfield":63,"defense":62,"goalkeeper":61,"overall":62},
  "Jagiellonia": {"attack":68,"midfield":69,"defense":68,"goalkeeper":65,"overall":68},
  "Lech Poznan": {"attack":69,"midfield":70,"defense":69,"goalkeeper":67,"overall":69},
  "Legia Warszawa": {"attack":70,"midfield":71,"defense":69,"goalkeeper":67,"overall":70},
  "Rakow Czestochowa": {"attack":70,"midfield":71,"defense":71,"goalkeeper":68,"overall":71},
  "Shamrock Rovers": {"attack":64,"midfield":65,"defense":64,"goalkeeper":63,"overall":64},
  "Shelbourne": {"attack":63,"midfield":64,"defense":63,"goalkeeper":62,"overall":63},
  "Universitatea Craiova": {"attack":67,"midfield":68,"defense":68,"goalkeeper":65,"overall":67},
  "Aberdeen": {"attack":68,"midfield":69,"defense":69,"goalkeeper":66,"overall":68},
  "Slovan Bratislava": {"attack":66,"midfield":67,"defense":66,"goalkeeper":64,"overall":66},
  "Celje": {"attack":65,"midfield":66,"defense":65,"goalkeeper":63,"overall":65},
  "Hacken": {"attack":68,"midfield":68,"defense":67,"goalkeeper":65,"overall":67},
  "Lausanne-Sport": {"attack":66,"midfield":67,"defense":67,"goalkeeper":64,"overall":66},
  "Samsunspor": {"attack":69,"midfield":70,"defense":69,"goalkeeper":67,"overall":69}
});

Object.assign(EUROPEAN_CLUB_PROFILES, {
  "LASK": {"attack":68,"midfield":69,"defense":68,"goalkeeper":66,"overall":68},
  "Sabah": {"attack":64,"midfield":65,"defense":63,"goalkeeper":62,"overall":64},
  "Viking": {"attack":67,"midfield":68,"defense":66,"goalkeeper":64,"overall":67},
  "Ararat-Armenia": {"attack":63,"midfield":64,"defense":63,"goalkeeper":61,"overall":63},
  "Hapoel Beer-Sheva": {"attack":66,"midfield":66,"defense":65,"goalkeeper":63,"overall":65},
  "Levski Sofia": {"attack":65,"midfield":66,"defense":64,"goalkeeper":62,"overall":64},
  "Lillestrom": {"attack":65,"midfield":66,"defense":64,"goalkeeper":62,"overall":64},
  "NEC": {"attack":69,"midfield":70,"defense":67,"goalkeeper":64,"overall":68},
  "OFI Crete": {"attack":64,"midfield":65,"defense":64,"goalkeeper":62,"overall":63},
  "Torreense": {"attack":63,"midfield":64,"defense":62,"goalkeeper":60,"overall":62},
  "Aarhus": {"attack":68,"midfield":69,"defense":67,"goalkeeper":65,"overall":67},
  "Borac": {"attack":62,"midfield":63,"defense":62,"goalkeeper":60,"overall":61},
  "CSKA Sofia": {"attack":64,"midfield":65,"defense":64,"goalkeeper":62,"overall":63},
  "Egnatia": {"attack":63,"midfield":64,"defense":62,"goalkeeper":60,"overall":62},
  "Gent": {"attack":71,"midfield":72,"defense":70,"goalkeeper":67,"overall":70},
  "Hajduk Split": {"attack":67,"midfield":68,"defense":66,"goalkeeper":64,"overall":66},
  "Hearts": {"attack":67,"midfield":68,"defense":67,"goalkeeper":64,"overall":66},
  "Iberia Tbilisi": {"attack":60,"midfield":61,"defense":60,"goalkeeper":58,"overall":59},
  "Inter Escaldes": {"attack":58,"midfield":59,"defense":58,"goalkeeper":56,"overall":57},
  "Jablonec": {"attack":65,"midfield":66,"defense":64,"goalkeeper":62,"overall":64},
  "Kauno Zalgiris": {"attack":60,"midfield":61,"defense":60,"goalkeeper":58,"overall":59},
  "Lugano": {"attack":68,"midfield":69,"defense":67,"goalkeeper":65,"overall":67},
  "Mjallby": {"attack":63,"midfield":64,"defense":62,"goalkeeper":60,"overall":62},
  "Nordsjaelland": {"attack":66,"midfield":68,"defense":64,"goalkeeper":62,"overall":65},
  "Riga": {"attack":61,"midfield":62,"defense":60,"goalkeeper":58,"overall":60},
  "Sint-Truidense": {"attack":66,"midfield":67,"defense":64,"goalkeeper":62,"overall":65},
  "Thun": {"attack":61,"midfield":62,"defense":60,"goalkeeper":58,"overall":60},
  "Twente": {"attack":70,"midfield":71,"defense":68,"goalkeeper":65,"overall":69}
});

// Association coefficients drive the historical dynasty entry allocation.
// They are intentionally normalized to a 0-100 scale so the allocation stays
// deterministic even when a historical club is represented by a rank profile.
const EUROPEAN_ASSOCIATION_COEFFICIENTS = {
  eng: 100,
  esp: 98,
  ita: 94,
  ger: 92,
  fra: 88,
  ned: 74,
  por: 72,
  bel: 66,
  tur: 63,
  gre: 58,
  aut: 55,
  cze: 53,
  sco: 50,
  sui: 48,
  ukr: 46,
  den: 44,
  pol: 42,
  nor: 40,
  cro: 38,
  srb: 37,
  isr: 35,
  hun: 33,
  rou: 31,
  swe: 30,
  cyp: 28,
  aze: 27,
  svn: 26,
  svk: 25,
  kaz: 24,
  fin: 22,
  isl: 20,
  bih: 19,
  mkd: 18,
  irl: 17,
  mlt: 15,
  kos: 14,
  bul: 23,
  arm: 12,
  gib: 10,
  other: 8
};

const EUROPEAN_CLUB_ASSOCIATIONS = {
  PSV: "ned",
  Ajax: "ned",
  Feyenoord: "ned",
  "Go Ahead Eagles": "ned",
  Utrecht: "ned",
  "AZ Alkmaar": "ned",
  "FC Porto": "por",
  Benfica: "por",
  "Sporting CP": "por",
  Braga: "por",
  "Union Saint-Gilloise": "bel",
  "Club Brugge": "bel",
  Genk: "bel",
  Galatasaray: "tur",
  "Fenerbahçe": "tur",
  Olympiacos: "gre",
  PAOK: "gre",
  Panathinaikos: "gre",
  "AEK Athens": "gre",
  Salzburg: "aut",
  "Sturm Graz": "aut",
  "SK Rapid": "aut",
  "Slavia Prague": "cze",
  "Viktoria Plzen": "cze",
  "Sparta Prague": "cze",
  "Sigma Olomouc": "cze",
  Celtic: "sco",
  Rangers: "sco",
  Aberdeen: "sco",
  Basel: "sui",
  "Young Boys": "sui",
  "Lausanne-Sport": "sui",
  Shakhtar: "ukr",
  "Dynamo Kyiv": "ukr",
  Copenhagen: "den",
  Midtjylland: "den",
  Jagiellonia: "pol",
  "Lech Poznan": "pol",
  "Legia Warszawa": "pol",
  "Rakow Czestochowa": "pol",
  "Bodø/Glimt": "nor",
  Brann: "nor",
  "Dinamo Zagreb": "cro",
  Rijeka: "cro",
  "Red Star": "srb",
  "Maccabi Tel-Aviv": "isr",
  "Ferencváros": "hun",
  Ludogorets: "bul",
  FCSB: "rou",
  "Universitatea Craiova": "rou",
  Malmö: "swe",
  "AEK Larnaca": "cyp",
  Omonoia: "cyp",
  Pafos: "cyp",
  Qarabag: "aze",
  Celje: "svn",
  "Slovan Bratislava": "svk",
  "Kairat Almaty": "kaz",
  KuPS: "fin",
  Breidablik: "isl",
  Zrinjski: "bih",
  Shkendija: "mkd",
  "Shamrock Rovers": "irl",
  Shelbourne: "irl",
  Drita: "kos",
  "Hamrun Spartans": "mlt",
  Noah: "arm",
  "Lincoln Red Imps": "gib",
  Hacken: "swe",
  Samsunspor: "tur"
};

const EUROPE_2026_27 = {
  UCL: [
    { name: "AEK Athens", profile: "AEK Athens", association: "gre" },
    { name: "Arsenal", id: "arsenal", association: "eng" },
    { name: "Aston Villa", id: "aston-villa", association: "eng" },
    { name: "Atleti", id: "atletico-de-madrid", association: "esp" },
    { name: "B. Dortmund", id: "borussia-dortmund", association: "ger" },
    { name: "Barcelona", id: "fc-barcelona", association: "esp" },
    { name: "Bayern Munchen", id: "fc-bayern-munchen", association: "ger" },
    { name: "Bodo/Glimt", profile: "Bodø/Glimt", association: "nor" },
    { name: "Club Brugge", profile: "Club Brugge", association: "bel" },
    { name: "Como", id: "como", association: "ita" },
    { name: "Fenerbahce", profile: "Fenerbahçe", association: "tur" },
    { name: "Feyenoord", profile: "Feyenoord", association: "ned" },
    { name: "Galatasaray", profile: "Galatasaray", association: "tur" },
    { name: "Inter", id: "inter-milan", association: "ita" },
    { name: "LASK", profile: "LASK", association: "aut" },
    { name: "Leipzig", id: "rb-leipzig", association: "ger" },
    { name: "Lens", id: "rc-lens", association: "fra" },
    { name: "Lille", id: "losc-lille", association: "fra" },
    { name: "Liverpool", id: "liverpool", association: "eng" },
    { name: "Man City", id: "manchester-city", association: "eng" },
    { name: "Man Utd", id: "man-utd", association: "eng" },
    { name: "Napoli", id: "ssc-napoli", association: "ita" },
    { name: "Paris", id: "paris-sg", association: "fra" },
    { name: "Porto", profile: "FC Porto", association: "por" },
    { name: "PSV", profile: "PSV", association: "ned" },
    { name: "Real Betis", id: "real-betis", association: "esp" },
    { name: "Real Madrid", id: "real-madrid", association: "esp" },
    { name: "Roma", id: "as-roma", association: "ita" },
    { name: "S. Bratislava", profile: "Slovan Bratislava", association: "svk" },
    { name: "Sabah", profile: "Sabah", association: "aze" },
    { name: "Shakhtar", profile: "Shakhtar", association: "ukr" },
    { name: "Slavia Praha", profile: "Slavia Prague", association: "cze" },
    { name: "Sporting CP", profile: "Sporting CP", association: "por" },
    { name: "Stuttgart", id: "vfb-stuttgart", association: "ger" },
    { name: "Viking", profile: "Viking", association: "nor" },
    { name: "Villarreal", id: "villarreal-cf", association: "esp" }
  ],
  UEL: [
    { name: "Anderlecht", profile: "Anderlecht", association: "bel" },
    { name: "Ararat-Armenia", profile: "Ararat-Armenia", association: "arm" },
    { name: "AZ Alkmaar", profile: "AZ Alkmaar", association: "ned" },
    { name: "Benfica", profile: "Benfica", association: "por" },
    { name: "Besiktas", profile: "Beşiktaş", association: "tur" },
    { name: "Bournemouth", id: "afc-bournemouth", association: "eng" },
    { name: "Celje", profile: "Celje", association: "svn" },
    { name: "Celta", id: "celta", association: "esp" },
    { name: "Celtic", profile: "Celtic", association: "sco" },
    { name: "Crystal Palace", id: "crystal-palace", association: "eng" },
    { name: "Ferencvaros", profile: "Ferencváros", association: "hun" },
    { name: "GNK Dinamo", profile: "Dinamo Zagreb", association: "cro" },
    { name: "Hapoel Beer-Sheva", profile: "Hapoel Beer-Sheva", association: "isr" },
    { name: "Hoffenheim", id: "tsg-hoffenheim", association: "ger" },
    { name: "Jagiellonia", profile: "Jagiellonia", association: "pol" },
    { name: "Juventus", id: "juventus", association: "ita" },
    { name: "Lech Poznan", profile: "Lech Poznan", association: "pol" },
    { name: "Leverkusen", id: "leverkusen", association: "ger" },
    { name: "Levski Sofia", profile: "Levski Sofia", association: "bul" },
    { name: "Lillestrom", profile: "Lillestrom", association: "nor" },
    { name: "Lyon", id: "ol", association: "fra" },
    { name: "Marseille", id: "om", association: "fra" },
    { name: "Milan", id: "ac-milan", association: "ita" },
    { name: "NEC", profile: "NEC", association: "ned" },
    { name: "OFI Crete", profile: "OFI Crete", association: "gre" },
    { name: "Olympiacos", profile: "Olympiacos", association: "gre" },
    { name: "Omonia", profile: "Omonoia", association: "cyp" },
    { name: "Real Sociedad", id: "real-sociedad", association: "esp" },
    { name: "Rennes", id: "stade-rennais-fc", association: "fra" },
    { name: "Salzburg", profile: "Salzburg", association: "aut" },
    { name: "Sparta Praha", profile: "Sparta Prague", association: "cze" },
    { name: "Sturm Graz", profile: "Sturm Graz", association: "aut" },
    { name: "Sunderland", id: "sunderland", association: "eng" },
    { name: "Torreense", profile: "Torreense", association: "por" },
    { name: "Union SG", profile: "Union Saint-Gilloise", association: "bel" },
    { name: "Viktoria Plzen", profile: "Viktoria Plzen", association: "cze" }
  ],
  UECL: [
    { name: "Aarhus", profile: "Aarhus", association: "den" },
    { name: "Ajax", profile: "Ajax", association: "ned" },
    { name: "Atalanta", id: "atalanta", association: "ita" },
    { name: "Borac", profile: "Borac", association: "bih" },
    { name: "Braga", profile: "Braga", association: "por" },
    { name: "Brann", profile: "Brann", association: "nor" },
    { name: "Brighton", id: "brighton", association: "eng" },
    { name: "Copenhagen", profile: "Copenhagen", association: "den" },
    { name: "Crvena Zvezda", profile: "Red Star", association: "srb" },
    { name: "CSKA Sofia", profile: "CSKA Sofia", association: "bul" },
    { name: "Egnatia", profile: "Egnatia", association: "alb" },
    { name: "Freiburg", id: "sc-freiburg", association: "ger" },
    { name: "Gent", profile: "Gent", association: "bel" },
    { name: "Getafe", id: "getafe-cf", association: "esp" },
    { name: "Hajduk Split", profile: "Hajduk Split", association: "cro" },
    { name: "Hearts", profile: "Hearts", association: "sco" },
    { name: "Iberia Tbilisi", profile: "Iberia Tbilisi", association: "geo" },
    { name: "Inter Escaldes", profile: "Inter Escaldes", association: "and" },
    { name: "Jablonec", profile: "Jablonec", association: "cze" },
    { name: "Kairat Almaty", profile: "Kairat Almaty", association: "kaz" },
    { name: "Kauno Zalgiris", profile: "Kauno Zalgiris", association: "ltu" },
    { name: "KuPS Kuopio", profile: "KuPS", association: "fin" },
    { name: "L. Red Imps", profile: "Lincoln Red Imps", association: "gib" },
    { name: "Lugano", profile: "Lugano", association: "sui" },
    { name: "Midtjylland", profile: "Midtjylland", association: "den" },
    { name: "Mjallby", profile: "Mjallby", association: "swe" },
    { name: "Monaco", id: "as-monaco", association: "fra" },
    { name: "Nordsjaelland", profile: "Nordsjaelland", association: "den" },
    { name: "Pafos", profile: "Pafos", association: "cyp" },
    { name: "Panathinaikos", profile: "Panathinaikos", association: "gre" },
    { name: "Riga", profile: "Riga", association: "lva" },
    { name: "Sint-Truidense", profile: "Sint-Truidense", association: "bel" },
    { name: "Thun", profile: "Thun", association: "sui" },
    { name: "Trabzonspor", profile: "Trabzonspor", association: "tur" },
    { name: "Twente", profile: "Twente", association: "ned" },
    { name: "U. Craiova", profile: "Universitatea Craiova", association: "rou" }
  ]
};
// UEFA publishes the final player registration lists after the 2026-09-02
// deadline. Keep this snapshot separate from the domestic 2025-26 player pool.
const EUROPEAN_REGISTRATION_CUTOFF = "2026-09-02";
const EUROPEAN_REGISTRATION_STATUS = "pending";
const EUROPEAN_REGISTRATION_LIST_VERSION = "2026-27-registration-pending";
// Replace this object with the final UEFA List A/B snapshot after the cutoff.
// Keys must match an entry id, profile, or name in EUROPE_2026_27.
const EUROPEAN_REGISTERED_SQUADS = Object.freeze({});

function getEuropeanRegisteredSquad(entry) {
  if (EUROPEAN_REGISTRATION_STATUS !== "final") return null;
  const keys = [entry?.id, entry?.profile, entry?.name].filter(Boolean);
  const key = keys.find((candidate) => Array.isArray(EUROPEAN_REGISTERED_SQUADS[candidate]));
  return key ? EUROPEAN_REGISTERED_SQUADS[key].map((player) => ({ ...player })) : [];
}
